services:

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: edgesentinel-mediamtx
    ports:
      - "8554:8554"    # RTSP
      - "8888:8888"    # HLS
      - "8889:8889"    # WebRTC
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    restart: unless-stopped

  ai-inference-service:
    build:
      context: ../../ai-inference-service
      dockerfile: Dockerfile
    container_name: edgesentinel-ai-service
    ports:
      - "8080:8080"
    volumes:
      - ../../models:/app/weights     # modelos compartilhados com o host
    environment:
      - OTEL_ENDPOINT=http://edgesentinel-otel-collector:4317
    depends_on:
      - otel-collector
    restart: unless-stopped

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: edgesentinel-otel-collector
    volumes:
      - ./otel-collector.yml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - prometheus
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: edgesentinel-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: edgesentinel-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=edgesentinel
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  grafana-data: